name: Keep Render Server Awake

on:
  schedule:
    - cron: "*/30 * * * *"  # 10분마다 실행 (크론 스케줄)

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send Ping Request
        run: curl -s https://fastapi-render-m0ga.onrender.com/ > /dev/null
